CREATE TABLE `campaign_setup_questions` (
  `id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `setup_area` enum('topic','intent','review_packet','rules_memory','final_review') NOT NULL,
  `question_text` text NOT NULL,
  `rationale` text NOT NULL,
  `recommended_answer` text,
  `priority` enum('hard_blocker','warning','clarity') NOT NULL,
  `status` enum('open','answered','dismissed') NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_setup_questions_campaign_idx` (`campaign_id`),
  CONSTRAINT `campaign_setup_questions_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `campaign_setup_answers` (
  `id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `question_id` varchar(64) NOT NULL,
  `author_user_id` varchar(64) NOT NULL,
  `setup_area` enum('topic','intent','review_packet','rules_memory','final_review') NOT NULL,
  `decision_title` varchar(255) NOT NULL,
  `answer_text` text NOT NULL,
  `status` enum('pending_owner_approval','approved','rejected') NOT NULL,
  `is_intentional_ambiguity` tinyint(1) NOT NULL DEFAULT 0,
  `is_context_override` tinyint(1) NOT NULL DEFAULT 0,
  `owner_edited_by_user_id` varchar(64),
  `approved_by_user_id` varchar(64),
  `approved_at` timestamp NULL,
  `rejected_by_user_id` varchar(64),
  `rejected_at` timestamp NULL,
  `rejection_reason` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_setup_answers_campaign_idx` (`campaign_id`),
  KEY `campaign_setup_answers_question_idx` (`question_id`),
  KEY `campaign_setup_answers_author_idx` (`author_user_id`),
  KEY `campaign_setup_answers_owner_edit_idx` (`owner_edited_by_user_id`),
  KEY `campaign_setup_answers_approved_by_idx` (`approved_by_user_id`),
  KEY `campaign_setup_answers_rejected_by_idx` (`rejected_by_user_id`),
  CONSTRAINT `campaign_setup_answers_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `campaign_setup_answers_question_fk` FOREIGN KEY (`question_id`) REFERENCES `campaign_setup_questions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `campaign_setup_answers_author_fk` FOREIGN KEY (`author_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `campaign_setup_answers_owner_edit_fk` FOREIGN KEY (`owner_edited_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `campaign_setup_answers_approved_by_fk` FOREIGN KEY (`approved_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `campaign_setup_answers_rejected_by_fk` FOREIGN KEY (`rejected_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `campaign_setup_decisions` (
  `id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `source_answer_id` varchar(64),
  `setup_area` enum('topic','intent','review_packet','rules_memory','final_review') NOT NULL,
  `title` varchar(255) NOT NULL,
  `value` text NOT NULL,
  `is_intentional_ambiguity` tinyint(1) NOT NULL DEFAULT 0,
  `is_context_override` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_setup_decisions_campaign_idx` (`campaign_id`),
  KEY `campaign_setup_decisions_answer_idx` (`source_answer_id`),
  CONSTRAINT `campaign_setup_decisions_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `campaign_setup_decisions_answer_fk` FOREIGN KEY (`source_answer_id`) REFERENCES `campaign_setup_answers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `campaign_knowledge_reports` (
  `id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `html` text NOT NULL,
  `status` enum('draft','approved') NOT NULL,
  `generated_at` timestamp NOT NULL,
  `approved_by_user_id` varchar(64),
  `approved_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_knowledge_reports_campaign_idx` (`campaign_id`),
  KEY `campaign_knowledge_reports_approved_by_idx` (`approved_by_user_id`),
  CONSTRAINT `campaign_knowledge_reports_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `campaign_knowledge_reports_approved_by_fk` FOREIGN KEY (`approved_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
