CREATE TABLE IF NOT EXISTS `returned_idea_lineage` (
  `id` varchar(64) NOT NULL,
  `idea_id` varchar(64) NOT NULL,
  `from_campaign_id` varchar(64) NOT NULL,
  `to_campaign_id` varchar(64) NOT NULL,
  `original_workflow_state` enum('submitted','general_idea','needs_employee_clarification','ready_for_rd_review','future_opportunity','inactive_idea','potential_idea') NOT NULL,
  `returned_workflow_state` enum('submitted','general_idea','needs_employee_clarification','ready_for_rd_review','future_opportunity','inactive_idea','potential_idea') NOT NULL,
  `return_reason_tag` varchar(64) NOT NULL,
  `return_reason` text NOT NULL,
  `returned_by_user_id` varchar(64) NULL,
  `returned_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `returned_idea_lineage_idea_idx` (`idea_id`),
  KEY `returned_idea_lineage_from_campaign_idx` (`from_campaign_id`),
  KEY `returned_idea_lineage_to_campaign_idx` (`to_campaign_id`),
  CONSTRAINT `returned_idea_lineage_idea_fk` FOREIGN KEY (`idea_id`) REFERENCES `ideas` (`id`) ON DELETE CASCADE,
  CONSTRAINT `returned_idea_lineage_from_campaign_fk` FOREIGN KEY (`from_campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `returned_idea_lineage_to_campaign_fk` FOREIGN KEY (`to_campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `returned_idea_lineage_returned_by_fk` FOREIGN KEY (`returned_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `campaign_retrospectives` (
  `id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `status` enum('skipped','started','completed') NOT NULL,
  `question_text` text NOT NULL,
  `answer_text` text NULL,
  `campaign_learning` text NULL,
  `evidence_summary` text NULL,
  `ai_decision_log_id` varchar(64) NULL,
  `started_by_user_id` varchar(64) NULL,
  `started_at` timestamp NULL,
  `completed_by_user_id` varchar(64) NULL,
  `completed_at` timestamp NULL,
  `skipped_by_user_id` varchar(64) NULL,
  `skipped_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_retrospectives_campaign_idx` (`campaign_id`, `created_at`),
  KEY `campaign_retrospectives_ai_log_idx` (`ai_decision_log_id`),
  CONSTRAINT `campaign_retrospectives_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `campaign_retrospectives_ai_log_fk` FOREIGN KEY (`ai_decision_log_id`) REFERENCES `ai_decision_logs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `campaign_retrospectives_started_by_fk` FOREIGN KEY (`started_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `campaign_retrospectives_completed_by_fk` FOREIGN KEY (`completed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `campaign_retrospectives_skipped_by_fk` FOREIGN KEY (`skipped_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `retrospective_global_context_proposals` (
  `id` varchar(64) NOT NULL,
  `source_campaign_id` varchar(64) NOT NULL,
  `source_retrospective_id` varchar(64) NULL,
  `target_context` enum('company_context','global_innovation_context') NOT NULL,
  `title` varchar(255) NOT NULL,
  `proposed_change` text NOT NULL,
  `evidence_summary` text NOT NULL,
  `status` enum('pending_manager_approval','approved','rejected') NOT NULL,
  `created_by_user_id` varchar(64) NOT NULL,
  `decided_by_user_id` varchar(64) NULL,
  `decided_at` timestamp NULL,
  `decision_reason` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `retrospective_global_context_proposals_campaign_idx` (`source_campaign_id`, `status`),
  KEY `retrospective_global_context_proposals_retrospective_idx` (`source_retrospective_id`),
  CONSTRAINT `retrospective_global_context_proposals_campaign_fk` FOREIGN KEY (`source_campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `retrospective_global_context_proposals_retrospective_fk` FOREIGN KEY (`source_retrospective_id`) REFERENCES `campaign_retrospectives` (`id`) ON DELETE SET NULL,
  CONSTRAINT `retrospective_global_context_proposals_created_by_fk` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `retrospective_global_context_proposals_decided_by_fk` FOREIGN KEY (`decided_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
