CREATE TABLE `context_documents` (
  `id` varchar(64) NOT NULL,
  `context_type` enum('company','global_innovation') NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `source_metadata` json NULL,
  `status` enum('draft','approved','superseded') NOT NULL,
  `created_by_user_id` varchar(64) NOT NULL,
  `approved_by_user_id` varchar(64) NULL,
  `approved_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `context_documents_type_status_idx` (`context_type`, `status`),
  KEY `context_documents_created_by_idx` (`created_by_user_id`),
  KEY `context_documents_approved_by_idx` (`approved_by_user_id`),
  CONSTRAINT `context_documents_created_by_fk` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `context_documents_approved_by_fk` FOREIGN KEY (`approved_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `global_context_change_proposals` (
  `id` varchar(64) NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `rationale` text NOT NULL,
  `proposed_by_user_id` varchar(64) NOT NULL,
  `status` enum('pending_manager_approval','approved','rejected') NOT NULL,
  `approved_context_id` varchar(64) NULL,
  `decided_by_user_id` varchar(64) NULL,
  `decided_at` timestamp NULL,
  `decision_reason` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `global_context_change_proposals_status_idx` (`status`),
  KEY `global_context_change_proposals_proposed_by_idx` (`proposed_by_user_id`),
  KEY `global_context_change_proposals_context_idx` (`approved_context_id`),
  KEY `global_context_change_proposals_decided_by_idx` (`decided_by_user_id`),
  CONSTRAINT `global_context_change_proposals_proposed_by_fk` FOREIGN KEY (`proposed_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `global_context_change_proposals_context_fk` FOREIGN KEY (`approved_context_id`) REFERENCES `context_documents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `global_context_change_proposals_decided_by_fk` FOREIGN KEY (`decided_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `context_impact_checks` (
  `id` varchar(64) NOT NULL,
  `source_context_id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `ai_decision_log_id` varchar(64) NULL,
  `impact_level` enum('no_impact','active_alert','draft_warning','draft_hard_blocker') NOT NULL,
  `summary` text NOT NULL,
  `recommended_resolution` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `context_impact_checks_context_idx` (`source_context_id`),
  KEY `context_impact_checks_campaign_idx` (`campaign_id`),
  KEY `context_impact_checks_ai_log_idx` (`ai_decision_log_id`),
  CONSTRAINT `context_impact_checks_context_fk` FOREIGN KEY (`source_context_id`) REFERENCES `context_documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `context_impact_checks_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `context_impact_checks_ai_log_fk` FOREIGN KEY (`ai_decision_log_id`) REFERENCES `ai_decision_logs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `context_change_alerts` (
  `id` varchar(64) NOT NULL,
  `impact_check_id` varchar(64) NOT NULL,
  `source_context_id` varchar(64) NOT NULL,
  `campaign_id` varchar(64) NOT NULL,
  `status` enum('open','resolved') NOT NULL,
  `summary` text NOT NULL,
  `recommended_resolution` text NOT NULL,
  `resolution_type` enum('no_impact','update_campaign_context','campaign_context_override','follow_up_question','escalate_to_manager') NULL,
  `resolution_note` text NULL,
  `resolved_by_user_id` varchar(64) NULL,
  `resolved_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `context_change_alerts_status_idx` (`status`),
  KEY `context_change_alerts_impact_idx` (`impact_check_id`),
  KEY `context_change_alerts_context_idx` (`source_context_id`),
  KEY `context_change_alerts_campaign_idx` (`campaign_id`),
  KEY `context_change_alerts_resolved_by_idx` (`resolved_by_user_id`),
  CONSTRAINT `context_change_alerts_impact_fk` FOREIGN KEY (`impact_check_id`) REFERENCES `context_impact_checks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `context_change_alerts_context_fk` FOREIGN KEY (`source_context_id`) REFERENCES `context_documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `context_change_alerts_campaign_fk` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `context_change_alerts_resolved_by_fk` FOREIGN KEY (`resolved_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
